config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  resources :rooms, only: [:index, :show] do
    resources :bookings, only: [:new, :create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :client
  belongs_to :room
end

app/models/client.rb
class Client < ApplicationRecord
  # belongs_to :rooms, through: :bookings
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @room = Room.find(params[:room_id])
    @booking = Booking.new
  end

  def create
    @room = Room.find(params[:room_id])
    @booking = Booking.new(booking_params)
    @booking.save
  end

  private

  def booking_params
    params.require(:booking).permit(:client, :room, :starts_at, :ends_at)

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="wrapper-image-pages height-vh">
<h1>KYVOS</h1>
<%= render 'shared/navbar' %>
<div class="container">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="booking-h2">
      <h2><%= @room.name %></h2>
      <div class="booking-form">
        <div class="booking-date-picker">
          <p>Sélectionnez vos dates</p>
          <div id="inner-form">
            <%= simple_form_for [@room, @booking], remote: true do |f| %>
              <%= f.input :starts_at, :label => "Arrivée", as: :string, required: false, input_html: {class: "datepicker"} %>
              <%= f.input :starts_at, :label => "Départ", as: :string, required: false, input_html: {class: "datepicker"} %>
              <%= f.submit "Confirmer", class: "btn button-black" %>
            <% end %>

<!--             <p><i class="fa fa-eur" aria-hidden="true"></i><%= @room.price %>€</p>
 -->          </div>
        </div>
        <div class="booking-image">
          <%= image_tag @room.photo %>
        </div>
      </div>
    </div>
  </div>
</div>

</div>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>KYVOS</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <link href="/assets/logo.png" rel="shortcut icon" type="image/x-icon" />

  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render "shared/banner" %>
<div class="wrapper">
  <div class="container">
    <div class="slogan">
      <%= image_tag 'logo.png' %>
      <p>Riches d'expériences fortes et variées, nous sommes fières de vous proposer un établissement extraordinaire, pour partager un moment hors du temps, afin de vous permettre de vous recentrer sur vous, et sur votre environnement.</p>
    </div>
  </div>
</div>
<div class="wrapper wrapper-image">
  <div class="container">
    <div class="sailing">
      <h3>Participez au soft opening du Kyvos lors de <br> la Kyvos Sailing Race</h3>
      <p>En avant première, profiter d'un confort exceptionnel pour assister dans les meilleurs <br>  conditions à la plus grande régate de France !</p>
      <%= link_to "En savoir plus", rooms_path, class: "btn btn-primary button-black" %>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<%#= render "shared/banner-pages" %>
<div class="wrapper-image-pages">
  <h1>KYVOS</h1>
  <%= render 'shared/navbar' %>
  <div class="container">
    <div class="rooms">
      <h3>Découvrez nos offres</h3>
      <div class="row">
        <% @rooms.each do |room| %>
          <%= render "shared/card", room: room %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="banner in-show" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= @room.photo %>);background-position: center;">
  <div class="banner-content">
    <h1><%= @room.name %></h1>
   <!-- if user is the creator of the room : -->
      <%= link_to "Réserver", new_room_booking_path(@room), class: "btn btn-primary button-black" %>
  </div>
</div>

<div class="container">
  <div class="room">
    <div class="camp">
      <div class="heading">
        <h2>Description de la chambre</h2>
      </div>
      <div id="price">
        <%= @room.price %>€
      </div>
  </div>
</div>

app/views/shared/_banner-pages.html.erb
<div class="banner-pages" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.3)), url('https://images.unsplash.com/photo-1506043959821-2eda767099c8?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=8516f569db6d6ddcbc8daae137d08216&auto=format&fit=crop&w=1867&q=80');">
    <h1>KYVOS</h1>
    <%= render 'shared/navbar' %>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.3)), url('<%= image_path 'home.jpg' %>');">
    <h1>KYVOS</h1>
    <%= render 'shared/navbar' %>
    <div class="banner-content">
      <p>Partagez une véritable expérience de sommeil</p>
      <%= link_to "Reservation", rooms_path, class: "btn btn-primary button-black" %>
    </div>
</div>

app/views/shared/_card.html.erb
<div class="col-xs-12 col-md-4">
  <%= link_to new_room_booking_path(room) do %>
    <div class="card">
      <div class="image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= room.photo %>');">
      </div>
      <div class="card-body">
        <p id="room-name"><%= room.name %></p>
        <p id="room-capacity">Pour <%= room.capacity %> personnes</p>
        <p id="room-price">À partir de <%= room.price %>€ la nuit</p>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_form.html.erb
<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <div class="form-background-white">
      <%= simple_form_for(@client) do |f| %>
        <div class="form-group">
          <%= f.input :name %>
        </div>
        <div class="form-btn">
          <%= f.submit "Update my profile", class: "btn btn-primary btn-lg in_page" %>
          <%= link_to "Back to profile", user_path(@user), class: "secondary-link" %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%= javascript_pack_tag 'uploadbtn' %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->


  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <%= link_to "Accueil", root_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Offres", rooms_path, class: "navbar-wagon-item navbar-wagon-link"  %>
    <a href="" class="navbar-wagon-item navbar-wagon-link">À propos</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link">Contact</a>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Offres", rooms_path %></li>
          <li><a href="#">À Propos</a></li>
          <li><a href="#">Contact</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Offres", rooms_path %></li>
        <li><a href="#">À Propos</a></li>
        <li><a href="#">Contact</a></li>
      </ul>
    </div>
  </div>
</div>